version: '3.8'
services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: 'well_com'
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234'
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  well_com_spring:
    image: well-com:latest
    restart: always
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/well_com
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"

volumes:
  dbdata:
